services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: josianne
      POSTGRES_PASSWORD: josianne
    volumes:
      - g3data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - g3net

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - g3net

volumes:
  g3data:

networks:
  g3net:
